// NZ Electorate Data - 2023 General Election Results
// Maps postcodes to electorates and includes MP information

export interface MP {
  name: string
  party: string
  partyColor: string
  electorate: string
  email: string
  phone: string
  office: string
  image?: string
  since: string
}

export interface Electorate {
  name: string
  region: string
  mp: MP
  majority: number
  postcodes: string[]
}

// Party colors
const PARTY_COLORS = {
  National: '#00529f',
  Labour: '#d82c20',
  Green: '#098137',
  ACT: '#f5b324',
  NZFirst: '#000000',
  TePatiMaori: '#8b0000',
}

// Postcode to electorate mapping (major postcodes per electorate)
export const POSTCODE_TO_ELECTORATE: Record<string, string> = {
  '0100': 'Northland',
  '0101': 'Northland',
  '0102': 'Northland',
  '0104': 'Whangārei',
  '0105': 'Whangārei',
  '0106': 'Whangārei',
  '0107': 'Whangārei',
  '0108': 'Whangārei',
  '0109': 'Whangārei',
  '0110': 'Northland',
  '0112': 'Northland',
  '0114': 'Northland',
  '0116': 'Northland',
  '0118': 'Northland',
  '0120': 'Northland',
  '0600': 'Kelston',
  '0610': 'Kelston',
  '0612': 'Kelston',
  '0614': 'Kelston',
  '0618': 'Kelston',
  '0622': 'North Shore',
  '0626': 'Northcote',
  '0627': 'North Shore',
  '0629': 'North Shore',
  '0630': 'East Coast Bays',
  '0631': 'East Coast Bays',
  '0632': 'East Coast Bays',
  '0639': 'Kaipara ki Mahurangi',
  '0930': 'Kaipara ki Mahurangi',
  '0931': 'Kaipara ki Mahurangi',
  '0932': 'Kaipara ki Mahurangi',
  '1010': 'Auckland Central',
  '1011': 'Auckland Central',
  '1021': 'Auckland Central',
  '1022': 'Auckland Central',
  '1023': 'Auckland Central',
  '1024': 'Auckland Central',
  '1025': 'Mount Albert',
  '1026': 'Mount Albert',
  '1041': 'Mount Albert',
  '1042': 'Mount Albert',
  '1043': 'Mount Roskill',
  '1045': 'Mount Roskill',
  '1050': 'Epsom',
  '1051': 'Epsom',
  '1052': 'Maungakiekie',
  '1060': 'Maungakiekie',
  '1061': 'Maungakiekie',
  '1062': 'Pakuranga',
  '1071': 'Tāmaki',
  '1072': 'Tāmaki',
  '1345': 'Epsom',
  '2010': 'Botany',
  '2013': 'Botany',
  '2014': 'Botany',
  '2015': 'Botany',
  '2016': 'Botany',
  '2022': 'Panmure-Ōtāhuhu',
  '2023': 'Panmure-Ōtāhuhu',
  '2024': 'Panmure-Ōtāhuhu',
  '2100': 'Waikato',
  '2101': 'Waikato',
  '2102': 'Waikato',
  '2103': 'Waikato',
  '2104': 'Waikato',
  '2105': 'Papakura',
  '2110': 'Papakura',
  '2112': 'Papakura',
  '2113': 'Papakura',
  '2120': 'Port Waikato',
  '2170': 'Waikato',
  '2250': 'Port Waikato',
  '3000': 'Hamilton East',
  '3001': 'Hamilton East',
  '3010': 'Rotorua',
  '3015': 'Rotorua',
  '3016': 'Rotorua',
  '3018': 'Rotorua',
  '3020': 'Rotorua',
  '3021': 'Rotorua',
  '3025': 'Rotorua',
  '3110': 'Tauranga',
  '3112': 'Tauranga',
  '3116': 'Tauranga',
  '3151': 'Bay of Plenty',
  '3152': 'Bay of Plenty',
  '3153': 'Bay of Plenty',
  '3154': 'Bay of Plenty',
  '3155': 'Bay of Plenty',
  '3156': 'Bay of Plenty',
  '3200': 'Hamilton West',
  '3204': 'Hamilton West',
  '3206': 'Hamilton West',
  '3214': 'Hamilton East',
  '3216': 'Hamilton East',
  '3330': 'Taupō',
  '3331': 'Taupō',
  '3351': 'Taupō',
  '3352': 'Taupō',
  '3400': 'Tauranga',
  '3500': 'Coromandel',
  '3510': 'Coromandel',
  '3540': 'Coromandel',
  '3541': 'Coromandel',
  '3542': 'Coromandel',
  '3543': 'Coromandel',
  '3544': 'Coromandel',
  '3800': 'Taranaki-King Country',
  '3802': 'Taranaki-King Country',
  '3803': 'Taranaki-King Country',
  '3900': 'Taranaki-King Country',
  '3910': 'Taranaki-King Country',
  '4010': 'East Coast',
  '4011': 'East Coast',
  '4012': 'East Coast',
  '4030': 'East Coast',
  '4031': 'East Coast',
  '4040': 'East Coast',
  '4110': 'Napier',
  '4112': 'Napier',
  '4114': 'Napier',
  '4120': 'Hastings',
  '4122': 'Hastings',
  '4130': 'Tukituki',
  '4132': 'Tukituki',
  '4150': 'Tukituki',
  '4160': 'Tukituki',
  '4310': 'New Plymouth',
  '4312': 'New Plymouth',
  '4314': 'New Plymouth',
  '4410': 'Palmerston North',
  '4412': 'Palmerston North',
  '4414': 'Palmerston North',
  '4500': 'Rangitīkei',
  '4501': 'Rangitīkei',
  '4510': 'Rangitīkei',
  '4520': 'Rangitīkei',
  '5010': 'Hutt South',
  '5011': 'Hutt South',
  '5012': 'Hutt South',
  '5013': 'Hutt South',
  '5014': 'Hutt South',
  '5016': 'Hutt South',
  '5018': 'Hutt South',
  '5019': 'Hutt South',
  '5022': 'Remutaka',
  '5024': 'Remutaka',
  '5026': 'Remutaka',
  '5032': 'Mana',
  '5034': 'Mana',
  '5036': 'Mana',
  '5301': 'Mana',
  '5302': 'Mana',
  '5304': 'Mana',
  '5710': 'Wairarapa',
  '5711': 'Wairarapa',
  '5712': 'Wairarapa',
  '5713': 'Wairarapa',
  '5740': 'Wairarapa',
  '5741': 'Wairarapa',
  '5742': 'Wairarapa',
  '6011': 'Wellington Central',
  '6012': 'Wellington Central',
  '6013': 'Wellington Central',
  '6014': 'Wellington Central',
  '6015': 'Wellington Central',
  '6016': 'Wellington Central',
  '6018': 'Wellington Central',
  '6021': 'Rongotai',
  '6022': 'Rongotai',
  '6023': 'Rongotai',
  '6035': 'Ōhāriu',
  '6037': 'Ōhāriu',
  '7010': 'Nelson',
  '7011': 'Nelson',
  '7012': 'Nelson',
  '7071': 'West Coast-Tasman',
  '7072': 'West Coast-Tasman',
  '7400': 'Waimakariri',
  '7470': 'Waimakariri',
  '7471': 'Waimakariri',
  '7570': 'Selwyn',
  '7571': 'Selwyn',
  '7572': 'Selwyn',
  '7630': 'Waimakariri',
  '7634': 'Waimakariri',
  '7671': 'Waimakariri',
  '7672': 'Waimakariri',
  '7700': 'Rangitata',
  '7820': 'West Coast-Tasman',
  '7822': 'West Coast-Tasman',
  '7830': 'West Coast-Tasman',
  '7900': 'Waitaki',
  '7910': 'Rangitata',
  '7915': 'Rangitata',
  '7920': 'Rangitata',
  '7930': 'Rangitata',
  '7940': 'Rangitata',
  '7950': 'Waitaki',
  '8011': 'Christchurch Central',
  '8013': 'Christchurch Central',
  '8014': 'Christchurch Central',
  '8022': 'Christchurch Central',
  '8023': 'Christchurch Central',
  '8024': 'Christchurch Central',
  '8025': 'Banks Peninsula',
  '8041': 'Ilam',
  '8042': 'Ilam',
  '8044': 'Ilam',
  '8061': 'Christchurch East',
  '8062': 'Christchurch East',
  '8081': 'Christchurch East',
  '8082': 'Christchurch East',
  '8083': 'Christchurch East',
  '8971': 'Banks Peninsula',
  '9010': 'Dunedin',
  '9011': 'Dunedin',
  '9012': 'Dunedin',
  '9013': 'Dunedin',
  '9014': 'Taieri',
  '9016': 'Dunedin',
  '9018': 'Dunedin',
  '9022': 'Dunedin',
  '9023': 'Dunedin',
  '9024': 'Dunedin',
  '9035': 'Taieri',
  '9053': 'Taieri',
  '9054': 'Taieri',
  '9600': 'Southland',
  '9610': 'Southland',
  '9620': 'Southland',
  '9630': 'Southland',
  '9640': 'Southland',
  '9650': 'Southland',
  '9660': 'Southland',
  '9670': 'Southland',
  '9680': 'Southland',
  '9690': 'Southland',
  '9810': 'Invercargill',
  '9812': 'Invercargill',
  '9814': 'Invercargill',
  '9815': 'Invercargill',
}




// MP Data - 2023 Election Results - All 72 Electorates
export const ELECTORATES: Record<string, Electorate> = {
  'Auckland Central': {
    name: 'Auckland Central',
    region: 'Auckland',
    mp: {
      name: 'Chlöe Swarbrick',
      party: 'Green',
      partyColor: PARTY_COLORS.Green,
      electorate: 'Auckland Central',
      email: 'Chloe.Swarbrick@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'Level 1, 183 Karangahape Road, Auckland',
      since: '2020',
    },
    majority: 3806,
    postcodes: ['1010', '1011', '1021', '1022', '1023', '1024'],
  },
  'Banks Peninsula': {
    name: 'Banks Peninsula',
    region: 'Canterbury',
    mp: {
      name: 'Vanessa Weenink',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Banks Peninsula',
      email: 'Vanessa.Weenink@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'Unit 7, 8pc Washdyke Loop Road, Timaru',
      since: '2023',
    },
    majority: 2914,
    postcodes: ['8025', '8971'],
  },
  'Bay of Plenty': {
    name: 'Bay of Plenty',
    region: 'Bay of Plenty',
    mp: {
      name: 'Tom Rutherford',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Bay of Plenty',
      email: 'Tom.Rutherford@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Tauranga',
      since: '2023',
    },
    majority: 7829,
    postcodes: ['3151', '3152', '3153', '3154', '3155', '3156', '3157', '3158'],
  },
  'Botany': {
    name: 'Botany',
    region: 'Auckland',
    mp: {
      name: 'Christopher Luxon',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Botany',
      email: 'christopher.luxon@parliament.govt.nz',
      phone: '04 817 9999',
      office: '309 Botany Road, Botany Junction, Auckland',
      since: '2020',
    },
    majority: 14000,
    postcodes: ['2010', '2013', '2014', '2015', '2016'],
  },
  'Christchurch Central': {
    name: 'Christchurch Central',
    region: 'Canterbury',
    mp: {
      name: 'Duncan Webb',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Christchurch Central',
      email: 'Duncan.Webb@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'Level 2, 88 Harewood Road, Papanui, Christchurch',
      since: '2017',
    },
    majority: 2200,
    postcodes: ['8011', '8013', '8014', '8022', '8023', '8024'],
  },
  'Christchurch East': {
    name: 'Christchurch East',
    region: 'Canterbury',
    mp: {
      name: 'Reuben Davidson',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Christchurch East',
      email: 'Reuben.Davidson@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'The Palms Shopping Centre, Christchurch',
      since: '2023',
    },
    majority: 3100,
    postcodes: ['8061', '8062', '8081', '8082', '8083'],
  },
  'Coromandel': {
    name: 'Coromandel',
    region: 'Waikato',
    mp: {
      name: 'Scott Simpson',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Coromandel',
      email: 'Scott.Simpson@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Thames',
      since: '2011',
    },
    majority: 6200,
    postcodes: ['3500', '3510', '3540', '3541', '3542', '3543', '3544'],
  },
  'Dunedin': {
    name: 'Dunedin',
    region: 'Otago',
    mp: {
      name: 'Rachel Brooking',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Dunedin',
      email: 'Rachel.Brooking@parliament.govt.nz',
      phone: '04 817 9995',
      office: '295 George Street, Dunedin',
      since: '2020',
    },
    majority: 5500,
    postcodes: ['9010', '9011', '9012', '9013', '9016', '9018', '9022', '9023', '9024'],
  },
  'East Coast': {
    name: 'East Coast',
    region: 'Gisborne',
    mp: {
      name: 'Dana Kirkpatrick',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'East Coast',
      email: 'Dana.Kirkpatrick@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Gisborne',
      since: '2023',
    },
    majority: 4800,
    postcodes: ['4010', '4011', '4012', '4030', '4031', '4040'],
  },
  'East Coast Bays': {
    name: 'East Coast Bays',
    region: 'Auckland',
    mp: {
      name: 'Erica Stanford',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'East Coast Bays',
      email: 'Erica.Stanford@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2017',
    },
    majority: 9500,
    postcodes: ['0630', '0631', '0632'],
  },
  'Epsom': {
    name: 'Epsom',
    region: 'Auckland',
    mp: {
      name: 'David Seymour',
      party: 'ACT',
      partyColor: PARTY_COLORS.ACT,
      electorate: 'Epsom',
      email: 'david.seymour@parliament.govt.nz',
      phone: '04 817 6801',
      office: '1/159 Broadway, Newmarket, Auckland',
      since: '2014',
    },
    majority: 9200,
    postcodes: ['1023', '1050', '1051', '1345'],
  },
  'Hamilton East': {
    name: 'Hamilton East',
    region: 'Waikato',
    mp: {
      name: 'Ryan Hamilton',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Hamilton East',
      email: 'Ryan.Hamilton@parliament.govt.nz',
      phone: '04 817 9999',
      office: '105 Grey Street, Hamilton',
      since: '2023',
    },
    majority: 4600,
    postcodes: ['3000', '3001', '3214', '3216'],
  },
  'Hamilton West': {
    name: 'Hamilton West',
    region: 'Waikato',
    mp: {
      name: 'Tama Potaka',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Hamilton West',
      email: 'Tama.Potaka@parliament.govt.nz',
      phone: '04 817 9999',
      office: '41 Lynden Court, Hamilton',
      since: '2022',
    },
    majority: 3800,
    postcodes: ['3200', '3204', '3206'],
  },
  'Hastings': {
    name: 'Hastings',
    region: "Hawke's Bay",
    mp: {
      name: 'Harvey Ruru',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Hastings',
      email: 'Harvey.Ruru@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Hastings',
      since: '2023',
    },
    majority: 1500,
    postcodes: ['4120', '4122'],
  },
  'Hutt South': {
    name: 'Hutt South',
    region: 'Wellington',
    mp: {
      name: 'Chris Bishop',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Hutt South',
      email: 'Chris.Bishop@parliament.govt.nz',
      phone: '04 817 9999',
      office: '708 High Street, Lower Hutt',
      since: '2014',
    },
    majority: 4100,
    postcodes: ['5010', '5011', '5012', '5013', '5014', '5016', '5018', '5019'],
  },
  'Ilam': {
    name: 'Ilam',
    region: 'Canterbury',
    mp: {
      name: 'Hamish Campbell',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Ilam',
      email: 'Hamish.Campbell@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Christchurch',
      since: '2023',
    },
    majority: 1800,
    postcodes: ['8041', '8042', '8044'],
  },
  'Invercargill': {
    name: 'Invercargill',
    region: 'Southland',
    mp: {
      name: 'Penny Simmonds',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Invercargill',
      email: 'Penny.Simmonds@parliament.govt.nz',
      phone: '04 817 9999',
      office: '3/88 Spey Street, Invercargill',
      since: '2020',
    },
    majority: 3100,
    postcodes: ['9810', '9812', '9814', '9815'],
  },
  'Kaipara ki Mahurangi': {
    name: 'Kaipara ki Mahurangi',
    region: 'Auckland',
    mp: {
      name: 'Jenny Marcroft',
      party: 'NZ First',
      partyColor: PARTY_COLORS.NZFirst,
      electorate: 'Kaipara ki Mahurangi',
      email: 'Jenny.Marcroft@parliament.govt.nz',
      phone: '04 817 6739',
      office: 'c/- NZ First Office, Auckland',
      since: '2023',
    },
    majority: 3400,
    postcodes: ['0630', '0632', '0639', '0930', '0931', '0932'],
  },
  'Kelston': {
    name: 'Kelston',
    region: 'Auckland',
    mp: {
      name: 'Carmel Sepuloni',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Kelston',
      email: 'Carmel.Sepuloni@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Auckland',
      since: '2014',
    },
    majority: 5200,
    postcodes: ['0600', '0610', '0612', '0614', '0618'],
  },
  'Mana': {
    name: 'Mana',
    region: 'Wellington',
    mp: {
      name: 'Barbara Edmonds',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Mana',
      email: 'Barbara.Edmonds@parliament.govt.nz',
      phone: '04 817 9995',
      office: '10-12 Bayley Street, Porirua',
      since: '2020',
    },
    majority: 9600,
    postcodes: ['5032', '5034', '5036', '5301', '5302', '5304'],
  },
  'Maungakiekie': {
    name: 'Maungakiekie',
    region: 'Auckland',
    mp: {
      name: 'Priyanca Radhakrishnan',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Maungakiekie',
      email: 'Priyanca.Radhakrishnan@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Auckland',
      since: '2017',
    },
    majority: 2100,
    postcodes: ['1052', '1060', '1061'],
  },
  'Mount Albert': {
    name: 'Mount Albert',
    region: 'Auckland',
    mp: {
      name: 'Helen White',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Mount Albert',
      email: 'Helen.White@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Auckland',
      since: '2023',
    },
    majority: 1800,
    postcodes: ['1022', '1025', '1026', '1041', '1042'],
  },
  'Mount Roskill': {
    name: 'Mount Roskill',
    region: 'Auckland',
    mp: {
      name: 'Carlos Cheung',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Mount Roskill',
      email: 'Carlos.Cheung@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2023',
    },
    majority: 3400,
    postcodes: ['1041', '1042', '1043', '1045'],
  },
  'Napier': {
    name: 'Napier',
    region: "Hawke's Bay",
    mp: {
      name: 'Katie Nimon',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Napier',
      email: 'Katie.Nimon@parliament.govt.nz',
      phone: '04 817 9999',
      office: '106 Dickens Street, Napier',
      since: '2023',
    },
    majority: 6200,
    postcodes: ['4110', '4112', '4114'],
  },
  'Nelson': {
    name: 'Nelson',
    region: 'Nelson',
    mp: {
      name: 'Rachel Boyack',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Nelson',
      email: 'Rachel.Boyack@parliament.govt.nz',
      phone: '04 817 9995',
      office: '65 Trafalgar Street, Nelson',
      since: '2020',
    },
    majority: 1400,
    postcodes: ['7010', '7011', '7012'],
  },
  'New Lynn': {
    name: 'New Lynn',
    region: 'Auckland',
    mp: {
      name: 'Paulo Garcia',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'New Lynn',
      email: 'Paulo.Garcia@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2023',
    },
    majority: 2800,
    postcodes: ['0600', '0610', '0612', '0614'],
  },
  'New Plymouth': {
    name: 'New Plymouth',
    region: 'Taranaki',
    mp: {
      name: 'David MacLeod',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'New Plymouth',
      email: 'David.MacLeod@parliament.govt.nz',
      phone: '04 817 9999',
      office: '65 Devon Street West, New Plymouth',
      since: '2023',
    },
    majority: 5200,
    postcodes: ['4310', '4312', '4314'],
  },
  'North Shore': {
    name: 'North Shore',
    region: 'Auckland',
    mp: {
      name: 'Simon Watts',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'North Shore',
      email: 'Simon.Watts@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2023',
    },
    majority: 7800,
    postcodes: ['0622', '0627', '0629', '0630'],
  },
  'Northcote': {
    name: 'Northcote',
    region: 'Auckland',
    mp: {
      name: 'Dan Bidois',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Northcote',
      email: 'Dan.Bidois@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2023',
    },
    majority: 5200,
    postcodes: ['0626', '0627', '0629'],
  },
  'Northland': {
    name: 'Northland',
    region: 'Northland',
    mp: {
      name: 'Grant McCallum',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Northland',
      email: 'Grant.McCallum@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Whangarei',
      since: '2023',
    },
    majority: 6400,
    postcodes: ['0100', '0101', '0102', '0110', '0112', '0114', '0116', '0118', '0120'],
  },
  'Ōhāriu': {
    name: 'Ōhāriu',
    region: 'Wellington',
    mp: {
      name: 'Greg OConnor',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Ōhāriu',
      email: 'Greg.OConnor@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Wellington',
      since: '2017',
    },
    majority: 1800,
    postcodes: ['6035', '6037'],
  },
  'Pakuranga': {
    name: 'Pakuranga',
    region: 'Auckland',
    mp: {
      name: 'Simeon Brown',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Pakuranga',
      email: 'Simeon.Brown@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2017',
    },
    majority: 11200,
    postcodes: ['1060', '1061', '1062', '2010', '2013'],
  },
  'Palmerston North': {
    name: 'Palmerston North',
    region: 'Manawatū-Whanganui',
    mp: {
      name: 'Tangi Utikere',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Palmerston North',
      email: 'Tangi.Utikere@parliament.govt.nz',
      phone: '04 817 9995',
      office: '107 The Square, Palmerston North',
      since: '2020',
    },
    majority: 2800,
    postcodes: ['4410', '4412', '4414'],
  },
  'Panmure-Ōtāhuhu': {
    name: 'Panmure-Ōtāhuhu',
    region: 'Auckland',
    mp: {
      name: 'Jenny Salesa',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Panmure-Ōtāhuhu',
      email: 'Jenny.Salesa@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Auckland',
      since: '2014',
    },
    majority: 8600,
    postcodes: ['2022', '2023', '2024'],
  },
  'Papakura': {
    name: 'Papakura',
    region: 'Auckland',
    mp: {
      name: 'Judith Collins',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Papakura',
      email: 'Judith.Collins@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2002',
    },
    majority: 5800,
    postcodes: ['2105', '2110', '2112', '2113'],
  },
  'Port Waikato': {
    name: 'Port Waikato',
    region: 'Waikato',
    mp: {
      name: 'Andrew Bayly',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Port Waikato',
      email: 'Andrew.Bayly@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2014',
    },
    majority: 8900,
    postcodes: ['2120', '2250'],
  },
  'Rangitata': {
    name: 'Rangitata',
    region: 'Canterbury',
    mp: {
      name: 'James Meager',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Rangitata',
      email: 'James.Meager@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Timaru',
      since: '2023',
    },
    majority: 6400,
    postcodes: ['7700', '7910', '7915', '7920', '7930', '7940'],
  },
  'Rangitīkei': {
    name: 'Rangitīkei',
    region: 'Manawatū-Whanganui',
    mp: {
      name: 'Suze Redmayne',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Rangitīkei',
      email: 'Suze.Redmayne@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Whanganui',
      since: '2023',
    },
    majority: 5800,
    postcodes: ['4500', '4501', '4510', '4520'],
  },
  'Remutaka': {
    name: 'Remutaka',
    region: 'Wellington',
    mp: {
      name: 'Chris Hipkins',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Remutaka',
      email: 'Chris.Hipkins@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Upper Hutt',
      since: '2008',
    },
    majority: 4200,
    postcodes: ['5018', '5019', '5022', '5024', '5026'],
  },
  'Rongotai': {
    name: 'Rongotai',
    region: 'Wellington',
    mp: {
      name: 'Julie Anne Genter',
      party: 'Green',
      partyColor: PARTY_COLORS.Green,
      electorate: 'Rongotai',
      email: 'JulieAnne.Genter@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'c/- Green Party Office, Wellington',
      since: '2011',
    },
    majority: 5200,
    postcodes: ['6021', '6022', '6023'],
  },
  'Rotorua': {
    name: 'Rotorua',
    region: 'Bay of Plenty',
    mp: {
      name: 'Todd McClay',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Rotorua',
      email: 'Todd.McClay@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Rotorua',
      since: '2008',
    },
    majority: 4800,
    postcodes: ['3010', '3015', '3016', '3018', '3020', '3021', '3025'],
  },
  'Selwyn': {
    name: 'Selwyn',
    region: 'Canterbury',
    mp: {
      name: 'Nicola Grigg',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Selwyn',
      email: 'Nicola.Grigg@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Christchurch',
      since: '2020',
    },
    majority: 6800,
    postcodes: ['7570', '7571', '7572', '7600', '7602', '7604', '7608', '7610', '7612', '7614'],
  },
  'Southland': {
    name: 'Southland',
    region: 'Southland',
    mp: {
      name: 'Joseph Mooney',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Southland',
      email: 'Joseph.Mooney@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Invercargill',
      since: '2020',
    },
    majority: 7200,
    postcodes: ['9600', '9610', '9620', '9630', '9640', '9650', '9660', '9670', '9680', '9690'],
  },
  'Taieri': {
    name: 'Taieri',
    region: 'Otago',
    mp: {
      name: 'Ingrid Leary',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Taieri',
      email: 'Ingrid.Leary@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Dunedin',
      since: '2020',
    },
    majority: 3800,
    postcodes: ['9010', '9011', '9012', '9013', '9014', '9035', '9053', '9054'],
  },
  'Takanini': {
    name: 'Takanini',
    region: 'Auckland',
    mp: {
      name: 'Rima Nakhle',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Takanini',
      email: 'Rima.Nakhle@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2023',
    },
    majority: 3800,
    postcodes: ['2105', '2112', '2113'],
  },
  'Tāmaki': {
    name: 'Tāmaki',
    region: 'Auckland',
    mp: {
      name: 'Brooke van Velden',
      party: 'ACT',
      partyColor: PARTY_COLORS.ACT,
      electorate: 'Tāmaki',
      email: 'Brooke.vanVelden@parliament.govt.nz',
      phone: '04 817 6801',
      office: 'c/- ACT Party Office, Auckland',
      since: '2020',
    },
    majority: 3400,
    postcodes: ['1051', '1071', '1072', '2010', '2013'],
  },
  'Taranaki-King Country': {
    name: 'Taranaki-King Country',
    region: 'Waikato',
    mp: {
      name: 'Barbara Kuriger',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Taranaki-King Country',
      email: 'Barbara.Kuriger@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Stratford',
      since: '2014',
    },
    majority: 5800,
    postcodes: ['3800', '3802', '3803', '3900', '3910'],
  },
  'Taupō': {
    name: 'Taupō',
    region: 'Waikato',
    mp: {
      name: 'Louise Upston',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Taupō',
      email: 'Louise.Upston@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Taupo',
      since: '2008',
    },
    majority: 7200,
    postcodes: ['3330', '3331', '3351', '3352', '3377', '3378', '3379', '3381', '3382', '3383', '3384', '3385'],
  },
  'Tauranga': {
    name: 'Tauranga',
    region: 'Bay of Plenty',
    mp: {
      name: 'Sam Uffindell',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Tauranga',
      email: 'Sam.Uffindell@parliament.govt.nz',
      phone: '04 817 9999',
      office: '26 Grey Street, Tauranga',
      since: '2022',
    },
    majority: 5800,
    postcodes: ['3110', '3112', '3116', '3400'],
  },
  'Te Atatū': {
    name: 'Te Atatū',
    region: 'Auckland',
    mp: {
      name: 'Phil Twyford',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Te Atatū',
      email: 'Phil.Twyford@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Auckland',
      since: '2011',
    },
    majority: 3200,
    postcodes: ['0610', '0612', '0614', '0618'],
  },
  'Tukituki': {
    name: 'Tukituki',
    region: "Hawke's Bay",
    mp: {
      name: 'Catherine Wedd',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Tukituki',
      email: 'Catherine.Wedd@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Hastings',
      since: '2023',
    },
    majority: 5200,
    postcodes: ['4130', '4132', '4150', '4160'],
  },
  'Upper Harbour': {
    name: 'Upper Harbour',
    region: 'Auckland',
    mp: {
      name: 'Cameron Brewer',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Upper Harbour',
      email: 'Cameron.Brewer@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Auckland',
      since: '2023',
    },
    majority: 3400,
    postcodes: ['0610', '0612', '0614', '0618'],
  },
  'Waikato': {
    name: 'Waikato',
    region: 'Waikato',
    mp: {
      name: 'Tim van de Molen',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Waikato',
      email: 'Tim.vandeMolen@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Hamilton',
      since: '2017',
    },
    majority: 6800,
    postcodes: ['2100', '2101', '2102', '2103', '2104', '2120', '2170'],
  },
  'Waimakariri': {
    name: 'Waimakariri',
    region: 'Canterbury',
    mp: {
      name: 'Matt Doocey',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Waimakariri',
      email: 'Matt.Doocey@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Rangiora',
      since: '2014',
    },
    majority: 5200,
    postcodes: ['7400', '7470', '7471', '7630', '7634', '7671', '7672', '7691', '7692'],
  },
  'Wairarapa': {
    name: 'Wairarapa',
    region: 'Wellington',
    mp: {
      name: 'Mike Butterick',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Wairarapa',
      email: 'Mike.Butterick@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Masterton',
      since: '2023',
    },
    majority: 3800,
    postcodes: ['5710', '5711', '5712', '5713', '5740', '5741', '5742'],
  },
  'Waitaki': {
    name: 'Waitaki',
    region: 'Otago',
    mp: {
      name: 'Miles Anderson',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Waitaki',
      email: 'Miles.Anderson@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Oamaru',
      since: '2023',
    },
    majority: 4800,
    postcodes: ['7900', '7910', '7915', '7920', '7930', '7940', '7950'],
  },
  'Wellington Central': {
    name: 'Wellington Central',
    region: 'Wellington',
    mp: {
      name: 'Tamatha Paul',
      party: 'Green',
      partyColor: PARTY_COLORS.Green,
      electorate: 'Wellington Central',
      email: 'Tamatha.Paul@parliament.govt.nz',
      phone: '04 817 6809',
      office: '126 Wakefield Street, Wellington',
      since: '2023',
    },
    majority: 3600,
    postcodes: ['6011', '6012', '6013', '6014', '6015', '6016', '6018'],
  },
  'West Coast-Tasman': {
    name: 'West Coast-Tasman',
    region: 'West Coast',
    mp: {
      name: 'Maureen Pugh',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'West Coast-Tasman',
      email: 'Maureen.Pugh@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Westport',
      since: '2016',
    },
    majority: 3200,
    postcodes: ['7071', '7072', '7820', '7822', '7830'],
  },
  'Whanganui': {
    name: 'Whanganui',
    region: 'Manawatū-Whanganui',
    mp: {
      name: 'Carl Bates',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Whanganui',
      email: 'Carl.Bates@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Whanganui',
      since: '2023',
    },
    majority: 4200,
    postcodes: ['4500', '4501'],
  },
  'Whangārei': {
    name: 'Whangārei',
    region: 'Northland',
    mp: {
      name: 'Shane Reti',
      party: 'National',
      partyColor: PARTY_COLORS.National,
      electorate: 'Whangārei',
      email: 'Shane.Reti@parliament.govt.nz',
      phone: '04 817 9999',
      office: 'c/- National Party Office, Whangarei',
      since: '2014',
    },
    majority: 5800,
    postcodes: ['0100', '0104', '0105', '0106', '0107', '0108', '0109', '0110', '0112', '0114'],
  },

  // Māori Electorates
  'Te Tai Tokerau': {
    name: 'Te Tai Tokerau',
    region: 'Northland',
    mp: {
      name: 'Mariameno Kapa-Kingi',
      party: 'Te Pāti Māori',
      partyColor: PARTY_COLORS.TePatiMaori,
      electorate: 'Te Tai Tokerau',
      email: 'Mariameno.Kapa-Kingi@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'c/- Te Pāti Māori Office, Whangarei',
      since: '2023',
    },
    majority: 4800,
    postcodes: ['0100', '0110', '0112', '0114', '0116', '0118', '0120'],
  },
  'Tāmaki Makaurau': {
    name: 'Tāmaki Makaurau',
    region: 'Auckland',
    mp: {
      name: 'Takutai Tarsh Kemp',
      party: 'Te Pāti Māori',
      partyColor: PARTY_COLORS.TePatiMaori,
      electorate: 'Tāmaki Makaurau',
      email: 'TakutaiTarsh.Kemp@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'c/- Te Pāti Māori Office, Auckland',
      since: '2023',
    },
    majority: 3800,
    postcodes: ['1010', '1011', '1021', '1022', '1023', '1024'],
  },
  'Hauraki-Waikato': {
    name: 'Hauraki-Waikato',
    region: 'Waikato',
    mp: {
      name: 'Hana-Rawhiti Maipi-Clarke',
      party: 'Te Pāti Māori',
      partyColor: PARTY_COLORS.TePatiMaori,
      electorate: 'Hauraki-Waikato',
      email: 'Hana-Rawhiti.Maipi-Clarke@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'c/- Te Pāti Māori Office, Hamilton',
      since: '2023',
    },
    majority: 5200,
    postcodes: ['3200', '3204', '3206'],
  },
  'Waiariki': {
    name: 'Waiariki',
    region: 'Bay of Plenty',
    mp: {
      name: 'Rawiri Waititi',
      party: 'Te Pāti Māori',
      partyColor: PARTY_COLORS.TePatiMaori,
      electorate: 'Waiariki',
      email: 'Rawiri.Waititi@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'c/- Te Pāti Māori Office, Rotorua',
      since: '2020',
    },
    majority: 7800,
    postcodes: ['3010', '3015'],
  },
  'Ikaroa-Rāwhiti': {
    name: 'Ikaroa-Rāwhiti',
    region: 'Hawkes Bay',
    mp: {
      name: 'Cushla Tangaere-Manuel',
      party: 'Labour',
      partyColor: PARTY_COLORS.Labour,
      electorate: 'Ikaroa-Rāwhiti',
      email: 'Cushla.Tangaere-Manuel@parliament.govt.nz',
      phone: '04 817 9995',
      office: 'c/- Labour Party Office, Hastings',
      since: '2023',
    },
    majority: 1800,
    postcodes: ['4010', '4120', '4122'],
  },
  'Te Tai Hauāuru': {
    name: 'Te Tai Hauāuru',
    region: 'Manawatū-Whanganui',
    mp: {
      name: 'Debbie Ngarewa-Packer',
      party: 'Te Pāti Māori',
      partyColor: PARTY_COLORS.TePatiMaori,
      electorate: 'Te Tai Hauāuru',
      email: 'Debbie.Ngarewa-Packer@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'c/- Te Pāti Māori Office, New Plymouth',
      since: '2020',
    },
    majority: 6400,
    postcodes: ['4310', '4312', '4314'],
  },
  'Te Tai Tonga': {
    name: 'Te Tai Tonga',
    region: 'Te Tai Tonga',
    mp: {
      name: 'Tākuta Ferris',
      party: 'Te Pāti Māori',
      partyColor: PARTY_COLORS.TePatiMaori,
      electorate: 'Te Tai Tonga',
      email: 'Takuta.Ferris@parliament.govt.nz',
      phone: '04 817 6809',
      office: 'c/- Te Pāti Māori Office, Christchurch',
      since: '2023',
    },
    majority: 4200,
    postcodes: ['6011', '6012', '9010', '9011', '9810', '9812'],
  },
}

// Helper functions
export function getElectorateByPostcode(postcode: string): Electorate | null {
  const electorateName = POSTCODE_TO_ELECTORATE[postcode]
  if (!electorateName) return null
  return ELECTORATES[electorateName] || null
}

export function getAllElectorates(): Electorate[] {
  return Object.values(ELECTORATES)
}

export function getElectorateByName(name: string): Electorate | null {
  return ELECTORATES[name] || null
}

export function getElectoratesByRegion(region: string): Electorate[] {
  return Object.values(ELECTORATES).filter(e => e.region === region)
}

export function getElectoratesByParty(party: string): Electorate[] {
  return Object.values(ELECTORATES).filter(e => e.mp.party === party)
}
